import type { ParameterGroup } from "./parameterMeta";

export type FieldType = "number" | "int" | "percent" | "euro" | "boolean" | "select" | "text" | "date";

export type ParamField = {
  path: string;
  label: string;
  help: string;
  unit?: string;
  type: FieldType;
  min?: number;
  max?: number;
  step?: number;
  options?: { value: string; label: string }[];
};

export type ParamGroup = {
  id: ParameterGroup;
  title: string;
  fields: ParamField[];
};

export const PARAM_GROUPS: ParamGroup[] = [
  {
    id: "general",
    title: "Allgemein",
    fields: [
      { path: "meta.name", label: "Szenarioname", help: "Bezeichnung dieses Simulationslaufs.", type: "text" },
      {
        path: "meta.description",
        label: "Beschreibung",
        help: "Kurze Einordnung. Keine Aussage über Scharia-Konformität.",
        type: "text",
      },
      {
        path: "seed",
        label: "Zufalls-Seed",
        help: "Gleiche Parameter und gleicher Seed erzeugen dasselbe Ergebnis.",
        type: "int",
        min: 1,
      },
      {
        path: "time.startDate",
        label: "Startdatum",
        help: "Erster Monat der Simulation.",
        type: "date",
      },
      {
        path: "time.horizonMonths",
        label: "Simulationsdauer",
        help: "Anzahl der simulierten Monate (z. B. 12, 24, 60, 120, 240).",
        type: "int",
        unit: "Monate",
        min: 1,
        max: 480,
      },
      {
        path: "time.loanOriginationStartMonth",
        label: "Startmonat Kreditvergabe",
        help: "Ab diesem Simulationsmonat dürfen Kredite ausgezahlt werden.",
        type: "int",
        min: 1,
        max: 480,
      },
    ],
  },
  {
    id: "members",
    title: "Mitglieder",
    fields: [
      {
        path: "population.mode",
        label: "Wachstumsmodus",
        help: "Fixe Mitgliederzahl oder dynamisches Wachstum.",
        type: "select",
        options: [
          { value: "fixed", label: "Mode A – feste Mitgliederzahl" },
          { value: "dynamic", label: "Mode B – dynamisches Wachstum" },
        ],
      },
      {
        path: "population.initialMembers",
        label: "Anfangsmitglieder",
        help: "Mitgliederbestand zu Beginn der Simulation.",
        type: "int",
        min: 0,
        max: 1_000_000,
      },
      {
        path: "population.maxMembers",
        label: "Maximale Mitgliederzahl",
        help: "Obergrenze für den Mitgliederbestand.",
        type: "int",
        min: 0,
        max: 1_000_000,
      },
      {
        path: "population.growth.type",
        label: "Wachstumstyp",
        help: "Konstant, prozentual, keine Veränderung oder Zeitreihe.",
        type: "select",
        options: [
          { value: "none", label: "Kein Wachstum" },
          { value: "constant", label: "Konstant (Personen/Monat)" },
          { value: "percent", label: "Prozentual" },
          { value: "timeseries", label: "Benutzerdefinierte Zeitreihe" },
        ],
      },
      {
        path: "population.growth.constantPerMonth",
        label: "Neue Mitglieder pro Monat",
        help: "Fixer Zugang, wenn Wachstumstyp „konstant“ gewählt ist.",
        type: "int",
        min: 0,
        max: 100000,
      },
      {
        path: "population.growth.percentPerMonth",
        label: "Monatliches Wachstum",
        help: "Prozentuales Wachstum des Bestands pro Monat.",
        type: "percent",
        min: 0,
        max: 50,
      },
      {
        path: "population.monthlyNoiseStdev",
        label: "Monatliche Schwankung",
        help: "Standardabweichung der Zufallsschwankung um den Wachstumswert (Modellannahme).",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "population.minMembershipMonthsForLoan",
        label: "Mindestalter Mitgliedschaft (Kredit)",
        help: "Monate Mitgliedschaft, bevor ein Kreditantrag möglich ist.",
        type: "int",
        unit: "Monate",
        min: 0,
        max: 120,
      },
      {
        path: "population.minMembershipMonthsBeforeExit",
        label: "Mindestmitgliedschaft vor Austritt",
        help: "Vorher sind in der Simulation keine Austritte möglich.",
        type: "int",
        unit: "Monate",
        min: 0,
        max: 120,
      },
      {
        path: "population.fixedModeReplacesExits",
        label: "Fixmodus ersetzt Austritte",
        help: "Bei fester Mitgliederzahl werden ausgetretene Personen durch neue ersetzt.",
        type: "boolean",
      },
      {
        path: "population.joinWave.enabled",
        label: "Einmalige Mitgliederwelle",
        help: "Zusätzlicher einmaliger Zugang in einem bestimmten Monat.",
        type: "boolean",
      },
      {
        path: "population.joinWave.month",
        label: "Welle: Monat",
        help: "Simulationsmonat der Mitgliederwelle.",
        type: "int",
        min: 1,
      },
      {
        path: "population.joinWave.extraMembers",
        label: "Welle: zusätzlichen Mitglieder",
        help: "Zusätzliche neue Mitglieder in diesem Monat.",
        type: "int",
        min: 0,
      },
    ],
  },
  {
    id: "contributions",
    title: "Beiträge",
    fields: [
      {
        path: "contributions.monthlyContributionCents",
        label: "Monatsbeitrag",
        help: "Gesamter Mitgliedsbeitrag (ohne Verwaltungsgebühr).",
        type: "euro",
        min: 0,
        max: 10000,
      },
      {
        path: "contributions.personalSavingsShareCents",
        label: "Persönlicher Anteil",
        help: "Anteil des Monatsbeitrags, der dem persönlichen Guthaben gutgeschrieben wird.",
        type: "euro",
        min: 0,
        max: 10000,
      },
      {
        path: "contributions.solidarityShareCents",
        label: "Solidaritätsfondsquote (Betrag)",
        help: "Anteil des monatlichen Mitgliedsbeitrags, der dem gemeinsamen Fonds zugeführt wird.",
        type: "euro",
        min: 0,
        max: 10000,
      },
    ],
  },
  {
    id: "personal",
    title: "Persönliche Guthaben",
    fields: [
      {
        path: "withdrawals.payoutRule",
        label: "Auszahlungsregel bei Austritt",
        help: "Wann das persönliche Guthaben ausgezahlt wird. Modellannahme.",
        type: "select",
        options: [
          { value: "immediate", label: "Sofort" },
          { value: "afterMonths", label: "Nach X Monaten" },
          { value: "fixedDeadline", label: "Nach definierter Frist" },
          { value: "installments", label: "Gestaffelt" },
        ],
      },
      {
        path: "withdrawals.payoutDelayMonths",
        label: "Auszahlungsverzögerung",
        help: "Monate bis zur Auszahlung (Regel „nach X Monaten“).",
        type: "int",
        min: 0,
        max: 60,
      },
      {
        path: "withdrawals.payoutDeadlineMonths",
        label: "Auszahlungsfrist",
        help: "Frist in Monaten bei fester Deadline.",
        type: "int",
        min: 0,
        max: 60,
      },
      {
        path: "withdrawals.installmentMonths",
        label: "Raten der gestaffelten Auszahlung",
        help: "Anzahl gleicher Auszahlungsraten.",
        type: "int",
        min: 1,
        max: 24,
      },
      {
        path: "withdrawals.exitsContributeInExitMonth",
        label: "Beitrag im Austrittsmonat",
        help: "Tritt ein Mitglied nach der Monatszahlung aus, zählt der Beitrag noch.",
        type: "boolean",
      },
    ],
  },
  {
    id: "fund",
    title: "Solidaritätsfonds",
    fields: [
      {
        path: "fund.initialCashCents",
        label: "Startbestand Fonds",
        help: "Anfängliches Solidaritätscash (nicht persönliches Guthaben).",
        type: "euro",
        min: 0,
      },
      {
        path: "fund.maximumLoanUtilization",
        label: "Maximale Fonds-Auslastung",
        help: "Maximaler Anteil der Fondsaktiva, der als offene Kredite gebunden sein darf. Standard-Modellannahme 70 %.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "fund.minimumFundReserve",
        label: "Mindest-Fondsreserve",
        help: "Mindestanteil der Fondsaktiva, der als Liquiditätsreserve bleibt. Standard-Modellannahme 30 %.",
        type: "percent",
        min: 0,
        max: 100,
      },
    ],
  },
  {
    id: "loans",
    title: "Kredite",
    fields: [
      {
        path: "loans.limitMethod",
        label: "Kreditlimit-Methode",
        help: "Wie das maximale Darlehen je Antrag bestimmt wird.",
        type: "select",
        options: [
          { value: "fixed", label: "Fixer Maximalbetrag" },
          { value: "tenure", label: "Nach Mitgliedschaftsdauer" },
          { value: "solidarityMultiple", label: "Solidaritätsbeiträge × Multiplikator" },
          { value: "personalMultiple", label: "Persönliches Guthaben × Multiplikator" },
          { value: "combined", label: "Minimum aller Grenzen" },
        ],
      },
      {
        path: "loans.maxProductCents",
        label: "Maximales Produktlimit",
        help: "Obergrenze je Kreditprodukt.",
        type: "euro",
        min: 0,
      },
      {
        path: "loans.solidarityMultiplier",
        label: "Multiplikator Solidaritätsbeiträge",
        help: "Credit Limit = kumulierte Solidaritätsbeiträge × Multiplikator.",
        type: "number",
        min: 0,
        max: 100,
        step: 0.5,
      },
      {
        path: "loans.personalMultiplier",
        label: "Multiplikator persönliches Guthaben",
        help: "Credit Limit = persönliches Guthaben × Multiplikator.",
        type: "number",
        min: 0,
        max: 100,
        step: 0.5,
      },
      {
        path: "loans.incomeMultiple",
        label: "Einkommensmultiplikator",
        help: "Optional: Limit relativ zum Monatseinkommen.",
        type: "number",
        min: 0,
        max: 60,
      },
      {
        path: "loans.incomeLimitEnabled",
        label: "Einkommenslimit aktiv",
        help: "Begrenzt den Kredit anhand des modellierten Einkommens.",
        type: "boolean",
      },
      {
        path: "loans.defaultTermMonths",
        label: "Standardlaufzeit",
        help: "Lineare Tilgung ohne Zinsen. Letzte Rate gleicht Rundung aus.",
        type: "int",
        unit: "Monate",
        min: 1,
        max: 120,
      },
      {
        path: "loans.repaymentModel",
        label: "Rückzahlungsmodell",
        help: "Standard ist lineare Tilgung. Alternative Modelle sind optional.",
        type: "select",
        options: [
          { value: "linear", label: "Lineare Tilgung" },
          { value: "grace", label: "Tilgungsfreie Anfangsphase" },
          { value: "flexible", label: "Flexible Tilgung (deaktiviert, falls nicht an)" },
          { value: "custom", label: "Individuell (deaktiviert, falls nicht an)" },
        ],
      },
      {
        path: "loans.alternativeRepaymentEnabled",
        label: "Alternative Rückzahlung aktiv",
        help: "Standardmäßig deaktiviert. Keine Zinsen, keine Gewinnmarge.",
        type: "boolean",
      },
      {
        path: "loans.graceMonths",
        label: "Tilgungsfreie Monate",
        help: "Nur wirksam, wenn alternative Rückzahlung aktiv ist.",
        type: "int",
        min: 0,
        max: 24,
      },
    ],
  },
  {
    id: "demand",
    title: "Kreditnachfrage",
    fields: [
      {
        path: "creditDemand.model",
        label: "Nachfragemodell",
        help: "Wie die Anzahl der Anträge je Monat bestimmt wird.",
        type: "select",
        options: [
          { value: "fixed", label: "Fixe Anzahl" },
          { value: "perMember", label: "Pro 1.000 Mitglieder" },
          { value: "byClass", label: "Nach Kreditklassen" },
          { value: "timeseries", label: "Zeitreihe" },
        ],
      },
      {
        path: "creditDemand.applicationsPerMonth",
        label: "Anträge pro Monat",
        help: "Fixe Nachfrage, unabhängig von der Mitgliederzahl.",
        type: "number",
        min: 0,
        max: 100000,
      },
      {
        path: "creditDemand.applicationsPerThousandMembers",
        label: "Anträge je 1.000 Mitglieder",
        help: "Skalierte Nachfrage relativ zum Bestand.",
        type: "number",
        min: 0,
        max: 500,
        step: 0.1,
      },
      {
        path: "creditDemand.averageAmountCents",
        label: "Durchschnittlicher Antrag",
        help: "Mittlerer gewünschter Kreditbetrag.",
        type: "euro",
        min: 0,
      },
      {
        path: "creditDemand.minAmountCents",
        label: "Mindestantrag",
        help: "Untere Grenze eines Antrags.",
        type: "euro",
        min: 0,
      },
      {
        path: "creditDemand.maxAmountCents",
        label: "Maximalantrag",
        help: "Obere Grenze eines Antrags.",
        type: "euro",
        min: 0,
      },
      {
        path: "creditDemand.demandGrowthPerMonth",
        label: "Nachfragewachstum",
        help: "Monatliches Wachstum der Nachfrage nach Start der Kreditvergabe.",
        type: "percent",
        min: -50,
        max: 50,
      },
    ],
  },
  {
    id: "approval",
    title: "Kreditvergabe",
    fields: [
      {
        path: "prioritization.strategy",
        label: "Priorisierungsstrategie",
        help: "Wer zuerst finanziert wird, wenn die Nachfrage die Kapazität übersteigt.",
        type: "select",
        options: [
          { value: "score", label: "Credit Score zuerst" },
          { value: "need", label: "Bedarf zuerst" },
          { value: "tenure", label: "Mitgliedschaftsdauer zuerst" },
          { value: "fifo", label: "FIFO" },
          { value: "weighted", label: "Gewichteter Score" },
        ],
      },
      {
        path: "prioritization.weightScore",
        label: "Gewicht Credit Score",
        help: "Anteil in der gewichteten Priorisierung.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "prioritization.weightNeed",
        label: "Gewicht Bedarf",
        help: "Anteil der Bedarfsklasse in der gewichteten Priorisierung.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "prioritization.weightTenure",
        label: "Gewicht Mitgliedschaftsdauer",
        help: "Anteil der Zugehörigkeit in der gewichteten Priorisierung.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "prioritization.weightFifo",
        label: "Gewicht Antragseingang",
        help: "Anteil FIFO in der gewichteten Priorisierung.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "creditApproval.minCreditScore",
        label: "Mindest-Credit-Score",
        help: "Anträge unter diesem Score werden abgelehnt. Interne Simulationsmetrik.",
        type: "number",
        min: 0,
        max: 200,
      },
      {
        path: "creditScore.membershipMax",
        label: "Score: Mitgliedschaft max.",
        help: "Maximalpunkte für Mitgliedschaftsdauer.",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        path: "creditScore.personalBalanceMax",
        label: "Score: persönliches Guthaben max.",
        help: "Maximalpunkte für das persönliche Guthaben.",
        type: "number",
        min: 0,
        max: 100,
      },
    ],
  },
  {
    id: "repayment",
    title: "Rückzahlung",
    fields: [
      {
        path: "delinquency.enabled",
        label: "Zahlungsverzug modellieren",
        help: "Verspätete Zahlungen ohne Verzugszinsen. Nur Liquiditäts-Timing.",
        type: "boolean",
      },
      {
        path: "delinquency.latePaymentRate",
        label: "Wahrscheinlichkeit verspäteter Zahlung",
        help: "Angenommener Anteil der Raten, der um einen Monat verschoben wird.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "delinquency.monthsUntilDefault",
        label: "Monate bis Ausfall nach Verzug",
        help: "Nach dieser Dauer gilt der überfällige Betrag als ausgefallen. Keine Verzugszinsen.",
        type: "int",
        min: 1,
        max: 12,
      },
    ],
  },
  {
    id: "defaults",
    title: "Ausfälle",
    fields: [
      {
        path: "defaults.model",
        label: "Ausfallmodell",
        help: "Wie die angenommene Ausfallquote angewendet wird.",
        type: "select",
        options: [
          { value: "constant", label: "Konstant" },
          { value: "byClass", label: "Nach Kreditklasse" },
          { value: "byTenure", label: "Nach Mitgliedsdauer" },
          { value: "byMonth", label: "Nach Monat" },
          { value: "byRemainingTerm", label: "Nach Restlaufzeit" },
          { value: "random", label: "Zufällig (Seed)" },
        ],
      },
      {
        path: "defaults.rateBasis",
        label: "Basis der Ausfallquote",
        help: "Jährlich wird intern durch 12 geteilt. Keine versteckte Umrechnung darüber hinaus.",
        type: "select",
        options: [
          { value: "annual", label: "Jährlich" },
          { value: "monthly", label: "Monatlich" },
        ],
      },
      {
        path: "defaults.constantRate",
        label: "Angenommene Ausfallquote",
        help: "Modellannahme, keine Prognose. Standard-Beispieldaten 3 % p. a.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "defaults.timing",
        label: "Ausfallzeitpunkt",
        help: "Wann ein Kredit in der Simulation ausfallen kann.",
        type: "select",
        options: [
          { value: "immediate", label: "Ab dem Folgemonat" },
          { value: "afterMonths", label: "Nach X Monaten" },
          { value: "nearEnd", label: "Kurz vor Ende" },
          { value: "random", label: "Zufällig über die Laufzeit" },
        ],
      },
      {
        path: "defaults.timingAfterMonths",
        label: "Ausfall nach Monaten",
        help: "Mindestalter des Kredits vor einem Ausfall.",
        type: "int",
        min: 0,
        max: 60,
      },
    ],
  },
  {
    id: "recovery",
    title: "Recovery",
    fields: [
      {
        path: "recovery.model",
        label: "Recovery-Modell",
        help: "Welcher Anteil einer ausgefallenen Restforderung später eingeht.",
        type: "select",
        options: [
          { value: "fixed", label: "Fixe Rate" },
          { value: "byClass", label: "Nach Kreditklasse" },
          { value: "byCollateral", label: "Nach Sicherheiten" },
          { value: "byTime", label: "Nach Zeit" },
          { value: "random", label: "Zufällig" },
        ],
      },
      {
        path: "recovery.fixedRate",
        label: "Angenommene Recovery-Rate",
        help: "Modellannahme. Beispiel: 70 % der Restforderung.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "recovery.lagMonths",
        label: "Recovery-Verzögerung",
        help: "Monate zwischen Ausfall und Recovery-Cashflow.",
        type: "int",
        min: 0,
        max: 24,
      },
    ],
  },
  {
    id: "exits",
    title: "Austritte",
    fields: [
      {
        path: "withdrawals.rateMode",
        label: "Austrittsmodus",
        help: "Prozentualer Anteil oder absolute Zahl.",
        type: "select",
        options: [
          { value: "percent", label: "Quote des Bestands" },
          { value: "fixedCount", label: "Fixe Austritte pro Monat" },
        ],
      },
      {
        path: "withdrawals.monthlyExitRate",
        label: "Monatliche Austrittsquote",
        help: "Angenommener Anteil der Mitglieder, der je Monat austritt.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "withdrawals.monthlyExitCount",
        label: "Fixe Austritte pro Monat",
        help: "Absolute Zahl, wenn der fixe Modus gewählt ist.",
        type: "int",
        min: 0,
      },
      {
        path: "withdrawals.shock.enabled",
        label: "Austritts-Schock",
        help: "Einmaliger prozentualer Austritt in einem Monat.",
        type: "boolean",
      },
      {
        path: "withdrawals.shock.month",
        label: "Schock-Monat",
        help: "Simulationsmonat des Austrittsschocks.",
        type: "int",
        min: 1,
      },
      {
        path: "withdrawals.shock.percentOfMembers",
        label: "Schock-Anteil",
        help: "z. B. 10 % der Mitglieder treten in diesem Monat aus.",
        type: "percent",
        min: 0,
        max: 100,
      },
    ],
  },
  {
    id: "liquidity",
    title: "Liquidität",
    fields: [
      {
        path: "liquidity.warningReserveRatio",
        label: "Warnschwelle Reserve",
        help: "Gelbe Warnung, wenn die Solidaritätsreserve darunter fällt.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "liquidity.minimumReserveRatio",
        label: "Mindestreserve (Warnung rot)",
        help: "Rote Warnung bei Unterschreitung.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "liquidity.minAbsoluteSolidarityCashCents",
        label: "Mindest-Solidaritätscash",
        help: "Absolute Untergrenze in Euro.",
        type: "euro",
        min: 0,
      },
      {
        path: "liquidity.coverageMonthsTarget",
        label: "Ziel-Liquiditätsreichweite",
        help: "Gewünschte Reichweite in Monaten (Anzeige, keine harte Engine-Grenze).",
        type: "number",
        min: 0,
        max: 60,
      },
    ],
  },
  {
    id: "admin",
    title: "Verwaltung",
    fields: [
      {
        path: "administration.feeMode",
        label: "Gebührenmodus",
        help: "Die Verwaltungsgebühr ist unabhängig von Kreditbetrag, Laufzeit und Restschuld.",
        type: "select",
        options: [
          { value: "fixed", label: "Fix je Mitglied" },
          { value: "schedule", label: "Zeitabhängig (ab Monat X)" },
          { value: "tiered", label: "Mitgliedschaftsstufen" },
        ],
      },
      {
        path: "administration.feePerMemberCents",
        label: "Verwaltungsgebühr je Mitglied",
        help: "Monatliche Gebühr, unabhängig vom Kredit.",
        type: "euro",
        min: 0,
        max: 1000,
      },
      {
        path: "administration.feeChangeMonth",
        label: "Gebührenänderung ab Monat",
        help: "Ab diesem Monat gilt die neue Gebühr (Zeitmodus).",
        type: "int",
        min: 1,
      },
      {
        path: "administration.feeAfterChangeCents",
        label: "Gebühr nach Änderung",
        help: "Neue monatliche Gebühr je Mitglied.",
        type: "euro",
        min: 0,
      },
    ],
  },
  {
    id: "crisis",
    title: "Krisen",
    fields: [
      {
        path: "events.0.enabled",
        label: "Ereignis Finanzkrise aktiv",
        help: "Wendet die konfigurierten Kriseneffekte über mehrere Monate an. Mehrere Ereignisse sind möglich.",
        type: "boolean",
      },
      {
        path: "events.0.startMonth",
        label: "Krise: Startmonat",
        help: "Beginn des Ereignisses.",
        type: "int",
        min: 1,
      },
      {
        path: "events.0.durationMonths",
        label: "Krise: Dauer",
        help: "Dauer in Monaten.",
        type: "int",
        min: 1,
        max: 120,
      },
      {
        path: "events.0.effects.defaultRateDelta",
        label: "Ausfallquote + Prozentpunkte",
        help: "Additiver Schock auf die angenommene jährliche Ausfallquote.",
        type: "percent",
        min: -50,
        max: 50,
      },
      {
        path: "events.0.effects.exitRateMultiplier",
        label: "Austritts-Multiplikator",
        help: "1,15 bedeutet +15 % auf die Austrittsquote.",
        type: "number",
        min: 0,
        max: 10,
        step: 0.05,
      },
      {
        path: "events.0.effects.demandMultiplier",
        label: "Nachfrage-Multiplikator",
        help: "1,5 bedeutet +50 % Kreditnachfrage.",
        type: "number",
        min: 0,
        max: 10,
        step: 0.05,
      },
      {
        path: "events.0.effects.newMembersMultiplier",
        label: "Neue-Mitglieder-Multiplikator",
        help: "0,7 bedeutet −30 % Zugänge.",
        type: "number",
        min: 0,
        max: 10,
        step: 0.05,
      },
      {
        path: "events.0.effects.recoveryDelta",
        label: "Recovery-Veränderung",
        help: "Additiv auf die Recovery-Rate, z. B. −20 Prozentpunkte.",
        type: "percent",
        min: -100,
        max: 100,
      },
      {
        path: "shocks.enabled",
        label: "Einmaliger Schock aktiv",
        help: "Mitglieder-, Ausfall-, Liquiditäts-, Nachfrage- oder Kostenschock in einem Monat.",
        type: "boolean",
      },
      {
        path: "shocks.month",
        label: "Schock-Monat",
        help: "Simulationsmonat des einmaligen Schocks.",
        type: "int",
        min: 1,
      },
      {
        path: "shocks.memberDropRate",
        label: "Mitglieder-Schock",
        help: "z. B. 20 % des Bestands.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "shocks.defaultShareOfOutstanding",
        label: "Ausfall-Schock offener Kredite",
        help: "Anteil der offenen Kredite, der in diesem Monat ausfällt.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "shocks.personalPayoutRate",
        label: "Liquiditätsschock persönliche Guthaben",
        help: "Anteil der persönlichen Guthaben, der gleichzeitig ausgezahlt werden soll.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "shocks.demandMultiplier",
        label: "Kreditnachfrage-Schock",
        help: "Multiplikator nur in diesem Monat.",
        type: "number",
        min: 0,
        max: 10,
      },
      {
        path: "shocks.adminCostMultiplier",
        label: "Verwaltungskosten-Schock",
        help: "Multiplikator der Kosten in diesem Monat.",
        type: "number",
        min: 0,
        max: 10,
      },
    ],
  },
  {
    id: "monteCarlo",
    title: "Monte Carlo",
    fields: [
      {
        path: "monteCarlo.runs",
        label: "Anzahl Simulationen",
        help: "Jede Run variiert Annahmen zufällig, aber reproduzierbar über den Seed.",
        type: "int",
        min: 10,
        max: 5000,
      },
      {
        path: "monteCarlo.seed",
        label: "Monte-Carlo-Seed",
        help: "Basis-Seed. Run i nutzt seed + i × 9973.",
        type: "int",
        min: 1,
      },
      {
        path: "monteCarlo.defaultRateVariation",
        label: "Variation Ausfallquote",
        help: "Relative Amplitude der Zufallsvariation.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "monteCarlo.exitRateVariation",
        label: "Variation Austrittsquote",
        help: "Relative Amplitude.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "monteCarlo.growthVariation",
        label: "Variation Wachstum",
        help: "Relative Amplitude.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "monteCarlo.demandVariation",
        label: "Variation Nachfrage",
        help: "Relative Amplitude.",
        type: "percent",
        min: 0,
        max: 100,
      },
      {
        path: "monteCarlo.recoveryVariation",
        label: "Variation Recovery",
        help: "Relative Amplitude.",
        type: "percent",
        min: 0,
        max: 100,
      },
    ],
  },
  {
    id: "advanced",
    title: "Erweitert",
    fields: [
      {
        path: "maxApplicationsMaterialized",
        label: "Max. materialisierte Anträge/Monat",
        help: "Performancegrenze. Darüber wird skaliert aggregiert.",
        type: "int",
        min: 10,
        max: 20000,
      },
      {
        path: "income.averageMonthlyIncomeCents",
        label: "Durchschnittseinkommen",
        help: "Modelliertes Monatseinkommen für Score und Limit.",
        type: "euro",
        min: 0,
      },
      {
        path: "income.averageMonthlyExpensesCents",
        label: "Durchschnittsausgaben",
        help: "Optionaler Faktor im Genehmigungsmodell.",
        type: "euro",
        min: 0,
      },
      {
        path: "loans.amountCapPolicy",
        label: "Über-Limit-Politik",
        help: "Antrag auf Limit kappen oder ablehnen.",
        type: "select",
        options: [
          { value: "capToLimit", label: "Auf Limit kappen" },
          { value: "reject", label: "Ablehnen" },
        ],
      },
    ],
  },
];
